### ISSUE TITLE
Should ERC4626 txs revert with zero amounts?

### ISSUE THREAD

**Issue by naddison36** [transmissions11/solmate#314]
[EIP-4626](https://eips.ethereum.org/EIPS/eip-4626) does not specify whether `deposit`, `mint`, `withdraw` or `redeem` transactions should revert or not if there are zero amounts.

I see the solmate implementation does the following
* `deposit` will revert if zero shares
* `mint` will NOT revert if zero assets
* `redeem` will revert if zero assets
* `withdraw` will NOT revert if zero shares

Personally, I think ERC4626 contracts should not revert if there are zero amounts returned.

Either way, I think solmate should be consistent with its handling of zero returned amounts of ERC4626 txs. They either all revert or all not revert.

**Comment by transmissions11** [comment]
its not about accepting or not accepting zero amounts, its about preventing users fro having their deposits rounded down to 0. that can't happen in the functions without zero checks because they round up.

**Comment by naddison36** [comment]
Excellent answer. Thanks
