### ISSUE TITLE
Purpose of checking if `returndatasize` is greater than 31 bytes in `SafeTransferLib`?

### ISSUE THREAD

**Issue by xenide** [transmissions11/solmate#361]
I'm curious regarding the purpose of checking for the return size being greater than 31 bytes. Is it to guard against implementations returning a `uint8` / `uint128` etc types instead of a bool? 

Besides, it doesn't guard against implementations which return a `uint256` type but of value `1` does it? 

For context, I had this question after referencing solady's [implementation](https://github.com/Vectorized/solady/blob/1e01e0d0e396e3bc6d70f5c27601ee86c77efe80/src/utils/SafeTransferLib.sol#L162), which doesn't check for the return type greater than 31 bytes.

**Comment by Vectorized** [comment]
@xenide Solady's implementation does indeed check that the `returndatasize` is greater than 31, albeit with some devious trickery.

In all the examples, as all the call function selectors does not end with the `0x01` byte, simply checking that slot `0x00` is rewritten to `0x0000000000000000000000000000000000000000000000000000000000000001` (i.e. 1) is sufficient to check that the `returndatasize` is indeed greater than 31.

**Comment by xenide** [comment]
got it, but both of these implementations don't really protect against an ERC20 that returns a `uint8` or `uint16` for example, if the contract is written using solidity. 

If the contract was using assembly or yul then it's possible to return less than 32 bytes. Correct?
